stages:
  - build
  - package

# ----------- Build MiniZincIDE -----------

build:linux:
  stage: build
  image: dekker1/minibuild:Qt
  script:
    - mkdir -p build; cd build
    - qmake -makefile "CONFIG+=bundled" "DEFINES+=MINIZINC_IDE_BUILD=\\\\\\\"\"${CI_PIPELINE_ID}\\\\\\\"\"" PREFIX=/usr ../MiniZincIDE/MiniZincIDE.pro
    - make -j4
    - make -j4 INSTALL_ROOT=../ide install; find ../ide/
    - cd ..
    - linuxdeployqt ide/usr/bin/MiniZincIDE -bundle-non-qt-libs -no-translations -no-copy-copyright-files
  tags:
    - linux
    - docker
  artifacts:
    paths:
      - ide/

build:osx:
  stage: build
  variables:
    QTDIR: "$OSXQTDIR"
  script:
    - mkdir -p build; cd build
    - qmake -makefile "CONFIG+=bundled" "DEFINES+=MINIZINC_IDE_BUILD=\\\\\\\"\"${CI_PIPELINE_ID}\\\\\\\"\"" ../MiniZincIDE/MiniZincIDE.pro
    - make -j4
    - cp -r MiniZincIDE.app ..
  tags:
    - osx
    - cpp
    - qt
  artifacts:
    paths:
      - MiniZincIDE.app

build:win64:
  stage: build
  variables:
    QTDIR: "$WINQTDIR"
  before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0/VC/vcvarsall.bat" amd64
  script:
    - if not exist "build" mkdir build
    - if not exist "ide" mkdir ide
    - cd build
    - echo set -x; export PATH=`cygpath -u %QTDIR%/bin`:$PATH; qmake "CONFIG+=bundled" "DEFINES+=MINIZINC_IDE_BUILD=\\\\\\\"\"${CI_PIPELINE_ID}\\\\\\\"\"" ../MiniZincIDE/MiniZincIDE.pro; nmake; cp release/MiniZincIDE.exe ../ide; cd ../ide; windeployqt --no-translations --no-compiler-runtime --no-system-d3d-compiler MiniZincIDE.exe > build.sh
    - d2u build.sh
    - bash build.sh
  tags:
    - win64
    - cpp
    - qt
  artifacts:
    paths:
      - ide/

# ----------- MiniZinc Packaging -----------
.packaging_setup: &packaging_setup
  before_script:
    ### Set the MZNVERSION variable
    - "if [ -n \"$CI_COMMIT_TAG\" ]; then MZNVERSION=\"$CI_COMMIT_TAG\"; else MZNVERSION=\"$CI_PIPELINE_ID\"; fi"
    ### Choose the MiniZinc compiler branch
    - "if [ -n \"$CI_COMMIT_TAG\" ]; then MZNREF=\"$CI_COMMIT_TAG\"; elif [ \"$CI_COMMIT_REF_NAME\" = \"master\" ]; then MZNREF=\"master\"; else MZNREF=\"develop\"; fi"
    ### Download Dependencies
    - curl --silent -o minizinc.zip --location --header "PRIVATE-TOKEN:$ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/minizinc%2Fminizinc/jobs/artifacts/$MZNREF/download?job=build:$MZNARCH"
    - unzip -q minizinc.zip
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:$ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/minizinc%2Fvendor/jobs/artifacts/master/download?job=solvers:$MZNARCH"
    - unzip -q vendor.zip
    - "[ ${DOWNLOAD_GLOBALIZER:-0} -eq 1 ] && curl --silent -o globalizer.zip --location --header \"PRIVATE-TOKEN:$ACCESS_TOKEN\" \"https://gitlab.com/api/v4/projects/minizinc%2FGlobalizer/jobs/artifacts/master/download?job=build:$MZNARCH\" && unzip -q globalizer.zip"
    - "[ ${DOWNLOAD_FINDMUS:-0} -eq 1 ] && curl --silent -o findmus.zip --location --header \"PRIVATE-TOKEN:$ACCESS_TOKEN\" \"https://gitlab.com/api/v4/projects/minizinc%2FFindMUS/jobs/artifacts/master/download?job=build:$MZNARCH\" && unzip -q findmus.zip"

package:linux:
  stage: package
  image: dekker1/minibuild:package
  variables:
    MZNARCH: "linux"
    DOWNLOAD_GLOBALIZER: 1
    DOWNLOAD_FINDMUS: 1
  <<: *packaging_setup
  script:
    - PACKAGE=MiniZincIDE-${MZNVERSION}-bundle-linux
    - mkdir -p $PACKAGE/
    ### Package IDE
    - mv ide/usr/* $PACKAGE/
    - cp resources/scripts/MiniZincIDE.sh $PACKAGE/
    ### Package MiniZinc
    - mv minizinc/bin/* $PACKAGE/bin/
    - mv minizinc/share $PACKAGE/share
    ### Replace mzn2fzn and solns2out by symlinks to reduce package size
    - rm $PACKAGE/bin/mzn2fzn $PACKAGE/bin/solns2out
    - (cd $PACKAGE/bin; ln -s minizinc mzn2fzn; ln -s minizinc solns2out)
    ### Package vendor solvers
    - mv vendor/gecode/bin/fzn-gecode $PACKAGE/bin/
    - mv vendor/gecode/share/gecode/mznlib $PACKAGE/share/minizinc/gecode
    - mv vendor/chuffed/bin/fzn-chuffed $PACKAGE/bin/
    - mv vendor/chuffed/share/chuffed/mznlib $PACKAGE/share/minizinc/chuffed
    ### Package Globalizer
    - mv globalizer/bin/minizinc-globalizer $PACKAGE/bin/
    - mv globalizer/share/globalizer/mznlib $PACKAGE/share/minizinc/globalizer
    ### Package findMUS
    - mv findMUS/bin/findMUS $PACKAGE/bin/
    ### Package solver scripts
    - cp resources/scripts/fzn-gecode-gist $PACKAGE/bin/
    ### Package default settings
    - mkdir -p $PACKAGE/share/minizinc/solvers/
    - cp resources/solvers/*.msc $PACKAGE/share/minizinc/solvers/
    - cp resources/Preferences.json $PACKAGE/share/minizinc/
    ### Strip included binaries
    - (cd $PACKAGE/bin; strip minizinc fzn-gecode fzn-chuffed findMUS minizinc-globalizer mzn2doc)
    - cp resources/misc/README $PACKAGE
    ### Compress package
    - tar -czf $PACKAGE.tgz $PACKAGE
  artifacts:
    name: "minizinc_bundle_linux_${CI_PIPELINE_ID}"
    paths:
      - MiniZincIDE*.tgz
  dependencies:
    - build:linux
  tags:
    - linux
    - docker

package:osx:
  stage: package
  variables:
    MZNARCH: "osx"
    DOWNLOAD_GLOBALIZER: 1
    DOWNLOAD_FINDMUS: 1
  <<: *packaging_setup
  script:
    - "DIR=MiniZincIDE.app/Contents/Resources; MZNDIR=$DIR/share/minizinc"
    - mkdir -p $MZNDIR/solvers
    ### Package MiniZinc
    - mv minizinc/bin/* $DIR/
    - mv minizinc/share/minizinc/* $MZNDIR/
    ### Replace mzn2fzn and solns2out by symlinks to reduce package size
    - rm $DIR/{mzn2fzn,solns2out}
    - (cd $DIR; ln -s minizinc mzn2fzn; ln -s minizinc solns2out)
    ### Package vendor solvers
    - mkdir -p $DIR/gecode
    - mv vendor/gecode/bin/fzn-gecode $DIR/gecode/
    - (cd $DIR; ln -s gecode/fzn-gecode)
    - mv vendor/gecode/share/gecode/mznlib $MZNDIR/gecode
    - mv vendor/chuffed/bin/fzn-chuffed $DIR/
    - mv vendor/chuffed/share/chuffed/mznlib $MZNDIR/chuffed
    ### Package Globalizer
    - mv globalizer/bin/minizinc-globalizer $DIR/
    - mv globalizer/share/globalizer/mznlib $MZNDIR/globalizer
    ### Package findMUS
    - mv findMUS/bin/findMUS $DIR/
    ### Package solver scripts
    - cp resources/scripts/fzn-gecode-gist $DIR/
    ### Package default settings
    - cp resources/solvers/*.msc $MZNDIR/solvers
    - cp resources/Preferences.json $MZNDIR/
    ### Run automated Qt deployment tool
    - macdeployqt ./MiniZincIDE.app -executable=$DIR/gecode/fzn-gecode
    ###### TODO: Fix is not necessary with Qt 5.11.1
    - GECODERPATHS=`otool -L ./MiniZincIDE.app/Contents/Resources/gecode/fzn-gecode | grep -o "@rpath\S*"`
    - for r in $GECODERPATHS; do LPATH=`sed -e 's|@rpath|@loader_path/../../Frameworks|' <<<"$r"`; install_name_tool -change $r $LPATH ./MiniZincIDE.app/Contents/Resources/gecode/fzn-gecode; done
  artifacts:
    name: "minizinc_bundle_mac_${CI_PIPELINE_ID}"
    paths:
      - MiniZincIDE.app
  dependencies:
    - build:osx
  tags:
     - osx
     - qt

package:win64:
  stage: package
  variables:
    MZNARCH: "win64"
    MSVCREDIST: "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/redist/x64/Microsoft.VC140.CRT"
    UCRTREDIST: "C:/Program Files (x86)/Windows Kits/10/Redist/ucrt/DLLs/x64"
    ISSARCH: "x64"
    ISSARCHALLOWED: "x64"
  before_script:
    ### Set the MZNVERSION variable
    - if defined CI_COMMIT_TAG (set MZNVERSION=%CI_COMMIT_TAG%) else (set MZNVERSION=%CI_PIPELINE_ID%)
    ### Choose the MiniZinc compiler branch
    - if defined CI_COMMIT_TAG (set MZNREF=%CI_COMMIT_TAG%) else if %CI_COMMIT_REF_NAME%==master (set MZNREF=master) else (set MZNREF=develop)
    ### Download Dependencies
    - curl --silent -o minizinc.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2Fminizinc/jobs/artifacts/%MZNREF%/download?job=build:%MZNARCH%"
    - unzip -q minizinc.zip
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2Fvendor/jobs/artifacts/master/download?job=solvers:%MZNARCH%"
    - unzip -q vendor.zip
    - curl --silent -o globalizer.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2Fglobalizer/jobs/artifacts/master/download?job=build:%MZNARCH%"
    - unzip -q globalizer.zip
    - curl --silent -o findmus.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2FFindMus/jobs/artifacts/master/download?job=build:%MZNARCH%"
    - unzip -q findmus.zip
  script:
    - "\"C:/Program Files (x86)/Inno Setup 5/ISCC.exe\" /dMyAppVersion=\"%MZNVERSION%\" /dMyMZNVersion=\"%MZNVERSION%\" /dMyAppDirectory=\"%CI_PROJECT_DIR%\" /dMyMSVCRedist=\"%MSVCREDIST%\" /dMyUCRTRedist=\"%UCRTREDIST%\" /dMyAPPArch=\"%MZNARCH%\" /dMyApp64Bit=\"%ISSARCH%\" /dMyAppArchitectures=\"%ISSARCHALLOWED%\" /O\"%CI_PROJECT_DIR%\" resources/pkg_config/MiniZincIDE-bundle.iss"
  artifacts:
    name: "minizinc_bundle_windows_%CI_PIPELINE_ID%"
    paths:
      - MiniZincIDE*.exe
  dependencies:
    - build:win64
  tags:
     - win64

package:docker_alpine:
  stage: package
  variables:
    MZNARCH: "musl"
  <<: *packaging_setup
  script:
    - docker build -f resources/pkg_config/Dockerfile.alpine -t minizinc_alpine .
    - if [ -n "$CI_COMMIT_TAG" ]; then docker tag minizinc_alpine minizinc/minizinc:$CI_COMMIT_TAG && docker push minizinc/minizinc:$CI_COMMIT_TAG; fi
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then docker tag minizinc_alpine minizinc/minizinc:latest && docker push minizinc/minizinc:latest; fi
    - docker tag minizinc_alpine minizinc/minizinc:edge && docker push minizinc/minizinc:edge 
  dependencies: []
  only:
    - master
    - develop
    - tags
  tags:
     - docker-cli

package:docker_ubuntu:
  stage: package
  variables:
    MZNARCH: "linux"
  <<: *packaging_setup
  script:
    - docker build -f resources/pkg_config/Dockerfile.ubuntu -t minizinc_ubuntu .
    - if [ -n "$CI_COMMIT_TAG" ]; then docker tag minizinc_ubuntu minizinc/minizinc:ubuntu_$CI_COMMIT_TAG && docker push minizinc/minizinc:ubuntu_$CI_COMMIT_TAG; fi
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then docker tag minizinc_ubuntu minizinc/minizinc:ubuntu_latest && docker push minizinc/minizinc:ubuntu_latest; fi
    - docker tag minizinc_ubuntu minizinc/minizinc:ubuntu_edge && docker push minizinc/minizinc:ubuntu_edge 
  dependencies: []
  only:
    - master
    - develop
    - tags
  tags:
     - docker-cli
