stages:
  - build
  - bundle

.win_build_template: &win_build_definition
  stage: build
  script:
    - if not exist "build" mkdir build
    - if not exist "ide" mkdir ide
    - cd build
    - echo set -x; export PATH=`cygpath -u %QTDIR%/bin`:$PATH; qmake "CONFIG+=bundled" "DEFINES+=MINIZINC_IDE_BUILD=\\\\\\\"\"${CI_PIPELINE_ID}\\\\\\\"\"" ../MiniZincIDE/MiniZincIDE.pro; nmake; cp release/MiniZincIDE.exe ../ide; cd ../ide; windeployqt MiniZincIDE.exe > build.sh
    - d2u build.sh
    - bash build.sh
  artifacts:
    paths:
      - ide/


build:linux:
  stage: build
  image: dekker1/qt:latest
  script:
    - mkdir -p build; cd build
    - qmake -makefile "CONFIG+=bundled" "DEFINES+=MINIZINC_IDE_BUILD=\\\\\\\"\"${CI_PIPELINE_ID}\\\\\\\"\"" ../MiniZincIDE/MiniZincIDE.pro
    - make -j4
    - mkdir -p ../ide/{bin,lib}; cd ../ide
    - cp ../build/MiniZincIDE bin/
    - cp $QTDIR/lib/{libQt5Widgets.so.5,libQt5WebEngineWidgets.so.5,libQt5WebEngineCore.so.5,libQt5Gui.so.5,libQt5Network.so.5,libQt5Core.so.5,libQt5PrintSupport.so.5,libQt5OpenGL.so.5,libQt5Quick.so.5,libQt5QuickWidgets.so.5,libQt5Qml.so.5,libQt5Sql.so.5,libQt5DBus.so.5,libQt5Svg.so.5,libQt5XcbQpa.so.5,libQt5Concurrent.so.5,libQt5Xml.so.5} $CI_PROJECT_DIR/ide/lib
    - cp /usr/lib/x86_64-linux-gnu/{libicui18n.so.55,libicuuc.so.55} $CI_PROJECT_DIR/ide/lib
    - cp -r $QTDIR/plugins $CI_PROJECT_DIR/ide/lib
  tags:
     - linux
     - docker
  artifacts:
    paths:
      - ide/
  cache:
    key: "linux_$CI_COMMIT_REF_SLUG"
    paths:
      - build/

build:osx:
  stage: build
  variables:
    QTDIR: "$OSXQTDIR"
  script:
    - export PATH="$QTDIR/bin:$PATH"
    - mkdir -p build; cd build
    - qmake -makefile "CONFIG+=bundled" "DEFINES+=MINIZINC_IDE_BUILD=\\\\\\\"\"${CI_PIPELINE_ID}\\\\\\\"\"" ../MiniZincIDE/MiniZincIDE.pro
    - make -j4
    - cp -r MiniZincIDE.app ..
  tags:
     - osx
     - cpp
     - qt
  artifacts:
    paths:
      - MiniZincIDE.app
  cache:
    key: "osx_$CI_COMMIT_REF_SLUG"
    paths:
      - build/

.build:win32: #DISABLED
  <<: *win_build_definition
  variables:
    QTDIR: "$WINQTDIR"
  before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0/VC/vcvarsall.bat"
  tags:
     - win32
     - cpp
     - qt
  cache:
    key: "win32_$CI_COMMIT_REF_SLUG"
    paths:
      - build/

build:win64:
  <<: *win_build_definition
  variables:
    QTDIR: "$WINQTDIR"
  before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0/VC/vcvarsall.bat" amd64
  tags:
     - win64
     - cpp
     - qt
  cache:
    key: "win64_$CI_COMMIT_REF_SLUG"
    paths:
      - build/
